title: frantic.im
author: Alex Kotliarskyi
author_tagline: a software engineering craftsman with interest in development experience
permalink: :title
email: contact@frantic.im
description: Occasional posts on technology and stuff
baseurl: ""
url: "http://frantic.im"
markdown: kramdown
highlighter: rouge
